version: "3.8"

services:
    app:
        build: .
        working_dir: /app
        ports: 
            - 3000:3000
        restart: "always"
        command: npm run preview
        container_name: app_vite